### ISSUE TITLE
Does not compile on RedHat EL 7

### ISSUE THREAD

**Issue by tuxpeople** [auth0/ad-ldap-connector#121]
Versions:
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Node: v10.2.1

Following https://auth0.com/docs/connector/install-other-platforms, npm install fails.

```
prebuild ERR! build error
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/opt/auth0-adldap/node_modules/node-gyp/lib/build.js:285:23)
prebuild ERR! stack     at ChildProcess.emit (events.js:182:13)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
prebuild ERR! not ok
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/opt/auth0-adldap/node_modules/node-gyp/lib/build.js:285:23)
prebuild ERR! build     at ChildProcess.emit (events.js:182:13)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: win-ca-ffi@github:jfromaniello/win-ca#support-other-stores (node_modules/win-ca-ffi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for win-ca-ffi@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules/ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.4.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-28T15_10_09_183Z-debug.log
```

**Comment by tuxpeople** [comment]
This fixed the issue for me:
```
npm install -g npm
```

**Comment by debdattam-hexaware** [comment]
My OS: RHEL 7.2

Getting same error while running npm install
Tried npm install -g npm
Still same error
Tried with both sudo and without sudo
------------
[chatbotadmin@CAMPUSCHATSERVER auth0-adldap]$ sudo npm install -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.8.0
added 54 packages from 9 contributors, removed 15 packages and updated 44 packages in 8.82s
[chatbotadmin@CAMPUSCHATSERVER auth0-adldap]$ npm install

> ref@1.3.5 install /home/chatbotadmin/auth0-adldap/node_modules/ref
> node-gyp rebuild

make: Entering directory `/home/chatbotadmin/auth0-adldap/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../../nan/nan.h:192:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^
In file included from ../src/binding.cc:7:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/node.h:176): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/node.h:169): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/node.h:162): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/node.h:176): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReadPointer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:253:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:2477): Use maybe version [-Wdeprecated-declarations]
   size_t size = info[2]->Uint32Value();
                                      ^
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteInt64(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:360:30: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:2891): Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value _str(in);
                              ^
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteUInt64(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:447:30: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:2891): Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value _str(in);
                              ^
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReinterpretBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:521:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:2477): Use maybe version [-Wdeprecated-declarations]
   size_t size = info[1]->Uint32Value();
                                      ^
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReinterpretBufferUntilZeros(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:550:44: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:2477): Use maybe version [-Wdeprecated-declarations]
   uint32_t numZeros = info[1]->Uint32Value();
                                            ^
In file included from ../../nan/nan.h:192:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:113:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/home/chatbotadmin/auth0-adldap/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-327.59.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chatbotadmin/auth0-adldap/node_modules/ref
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> leveldown@1.9.0 install /home/chatbotadmin/auth0-adldap/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.1 runtime=node arch=x64 platform=linux)
make: Entering directory `/home/chatbotadmin/auth0-adldap/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../node_modules/nan/nan.h:192:0,
                 from ../src/batch.cc:3:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^
In file included from ../src/batch.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/node.h:176): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/node.h:169): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/node.h:162): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../node_modules/nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/node.h:176): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h: In function ‘size_t StringOrBufferLength(v8::Local<v8::Value>)’:
../src/leveldown.h:16:26: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
   return (!obj->ToObject().IsEmpty()
                          ^
../src/leveldown.h:17:48: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     && node::Buffer::HasInstance(obj->ToObject()))
                                                ^
../src/leveldown.h:18:42: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     ? node::Buffer::Length(obj->ToObject())
                                          ^
In file included from ../src/batch.cc:8:0:
../src/common.h: In function ‘uint32_t leveldown::UInt32OptionValue(v8::Local<v8::Object>, const char*, uint32_t)’:
../src/common.h:32:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:2477): Use maybe version [-Wdeprecated-declarations]
     ? options->Get(key)->Uint32Value()
                                      ^
../src/batch.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE leveldown::Batch::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/batch.cc:42:76: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
   Database* database = Nan::ObjectWrap::Unwrap<Database>(info[0]->ToObject());
                                                                            ^
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/batch.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE leveldown::Batch::Put(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/leveldown.h:53:30: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
   } else if (!from->ToObject().IsEmpty()                                       \
                              ^
../src/batch.cc:91:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/leveldown.h:54:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
       && node::Buffer::HasInstance(from->ToObject())) {                        \
                                                   ^
../src/batch.cc:91:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/leveldown.h:55:53: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                                     ^
../src/batch.cc:91:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/leveldown.h:56:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                                   ^
../src/batch.cc:91:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/leveldown.h:53:30: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
   } else if (!from->ToObject().IsEmpty()                                       \
                              ^
../src/batch.cc:92:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
   ^
../src/leveldown.h:54:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
       && node::Buffer::HasInstance(from->ToObject())) {                        \
                                                   ^
../src/batch.cc:92:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
   ^
../src/leveldown.h:55:53: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                                     ^
../src/batch.cc:92:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
   ^
../src/leveldown.h:56:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                                   ^
../src/batch.cc:92:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
   ^
../src/batch.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE leveldown::Batch::Del(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/leveldown.h:53:30: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
   } else if (!from->ToObject().IsEmpty()                                       \
                              ^
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/leveldown.h:54:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
       && node::Buffer::HasInstance(from->ToObject())) {                        \
                                                   ^
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/leveldown.h:55:53: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                                     ^
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/leveldown.h:56:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/chatbotadmin/.node-gyp/10.15.1/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                                   ^
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/home/chatbotadmin/auth0-adldap/node_modules/leveldown/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-327.59.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chatbotadmin/auth0-adldap/node_modules/leveldown
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: win-ca-ffi@github:jfromaniello/win-ca#support-other-stores (node_modules/win-ca-ffi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for win-ca-ffi@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: win-ca-ffi@1.1.0 (node_modules/win-ca/node_modules/win-ca-ffi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for win-ca-ffi@1.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules/ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.9.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chatbotadmin/.npm/_logs/2019-02-27T10_26_12_016Z-debug.log
[chatbotadmin@CAMPUSCHATSERVER auth0-adldap]$ sudo npm install

> leveldown@1.9.0 install /home/chatbotadmin/auth0-adldap/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/chatbotadmin/auth0-adldap/node_modules/leveldown/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/chatbotadmin/auth0-adldap/node_modules/leveldown/.node-gyp'
gyp ERR! System Linux 3.10.0-327.59.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chatbotadmin/auth0-adldap/node_modules/leveldown
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: win-ca-ffi@github:jfromaniello/win-ca#support-other-stores (node_modules/win-ca-ffi):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Command failed: git clone --depth=1 -q -b support-other-stores git://github.com/jfromaniello/win-ca.git /root/.npm/_cacache/tmp/git-clone-e57c0eb6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e57c0eb6': Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: win-ca-ffi@1.1.0 (node_modules/win-ca/node_modules/win-ca-ffi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for win-ca-ffi@1.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.9.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-27T10_26_45_593Z-debug.log
[chatbotadmin@CAMPUSCHATSERVER auth0-adldap]$
