### ISSUE TITLE
Recent update to cookie-sessions breaks npm install

### ISSUE THREAD

**Issue by nmaclennan** [auth0/ad-ldap-connector#134]
It looks like [auth0/cookie-sessions@master](https://github.com/auth0/cookie-sessions/tree/master) was updated a bunch in the past few days but `package.json:34` is pinned to master, so the hash in npm-shrinkwrap is now incorrect, preventing `npm install` from completing.

https://github.com/auth0/ad-ldap-connector/blob/086d0cab8288d4e27e634b03ee374101ab581456/package.json#L34

**Comment by jfromaniello** [comment]
Thank you for reporting this. I just fixed it in version `v4.1.6`.
