### ISSUE TITLE
Avoid use of git: URLs for npm libraries

### ISSUE THREAD

**Issue by irobertson** [auth0/ad-ldap-connector#136]
package.json refers to two packages via a git: URL instead of an https: one: 

```
    "passport-ssl-certificate": "git://github.com/jaredhanson/passport-ssl-certificate.git#826c16d040841ec4b20db1a4cfe8bac81c931462",
    "win-ca-ffi": "github:jfromaniello/win-ca#support-other-stores"
```

Additionally, npm-shrinkwrap contains the following URLs:

```
      "version": "git://github.com/jaredhanson/passport-ssl-certificate.git#826c16d040841ec4b20db1a4cfe8bac81c931462",
      "from": "passport-ssl-certificate@git://github.com/jaredhanson/passport-ssl-certificate.git#826c16d040841ec4b20db1a4cfe8bac81c931462",
      "version": "github:crigot/stream-rotate#31fe967e6b1d5fdbaf641091877e39e54ae0dd8c",
      "from": "stream-rotate@github:crigot/stream-rotate#31fe967e6b1d5fdbaf641091877e39e54ae0dd8c",
      "resolved": "github:jfromaniello/win-ca#f5a9fcd99fba90b4647b1f043c56fe970a971dd3",
```

Use of these URLs is problematic in at least two ways. The first is that some companies firewall off the git port, where as the https port is not restricted. More significant, however, is the fact that the git: protocol uses no encryption, and hence is vulnerable to man-in-the-middle attacks.

Additionally, I believe the two "from" attributes in npm-shrinkwrap are non-sensical; the attribute is not defined as part of the format, per https://docs.npmjs.com/files/package-lock.json.

**Comment by jfromaniello** [comment]
I will prefer to stick to `github:user/repo#tag` method, which is what every repository for node.js uses.

It is not using the git protocol but rather SSH (which is encrypted).

I understand that this can be blocked as well behind a firewall, would you mind to test this workaround instead:

https://github.com/npm/npm/issues/5257#issuecomment-60441477

This way npm install will work for you for every nodejs project

**Comment by irobertson** [comment]
Thank you - the workaround you referenced worked, although moving past that exposed another issue, which I'll raise in a separate ticket.
