### ISSUE TITLE
Cannot start on Windows if Certificate Store contains a ECDSA certificate

### ISSUE THREAD

**Issue by philomory** [auth0/ad-ldap-connector#150]
If the Windows Certificate Store contains any certificates signed using any algorithm other than RSA, such as ECDSA, then the Auth0 AD LDAP Connector will fail to start. The error log will contain the message, `Error: Cannot read public key. OID is not RSA.`

An example of such a certificate is the `DigiCert Global Root G3`, described here: https://global-root-g3.chain-demos.digicert.com/info/index.html

This issue traces to the `win-ca` library, and is noted in their readme: https://github.com/ukoloff/win-ca#api ; ultimately the issue traces to the `forge` certificate-handling library, specifically digitalbazaar/forge#532

Unfortunately, ad-ldap-connector doesn't use the official `win-ca`, it uses a custom fork by @jfromaniello which, while it adds a useful feature, is 89 commits behind the official master. On this custom branch, simply requiring the library immediately causes the problem, without any chance to use the workarounds ukoloff has added.

I'm not really sure how to proceed, at this point. Ideally I'd love to have this certificate just get skipped when reading the certificate store, but with the fork of win-ca we're using, there doesn't seem to be any way to accomplish that.

**Comment by jfromaniello** [comment]
Thank you very much for reporting this @philomory and for the good and detailed explanation!

I missed the notification for this issue, we will try to fix as soon as possible.

**Comment by Maffsie** [comment]
Hi, is there any estimate on when this will be patched? We're still stuck on v3.9.1 due to this bug.

**Comment by jfromaniello** [comment]
It should be fixed in last version `v4.2.2`
