### ISSUE TITLE
Protect customer-modified adldap connector files from connector updates

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/ad-ldap-connector#27]
Provide a recommended way for customers to make needed changes to ADLDAP connector files and protect those changes from future ADLDAP connector patches/updates.
Files which may have been modified by customer might include the following, but there may be more?
- Certificate files
- config.json
- lib\profileMapper.js

It should be possible for customer to specify mapping of attributes between AD/LDAP source directory and the connector/Auth0 in a way that will be preserved when ADLDAP connector updates are applied to the connector server.  (ideally without customer having to manually save and restore the files)

**Comment by twistedstream** [comment]
@yvonnewilson: I think we can close out this old issue as the Connector's upgrade feature now (and has for some time) supported the preservation of all these files.
