### ISSUE TITLE
Support self-signed cert checking for AD connector running on Ubuntu

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/ad-ldap-connector#41]
Enable use of self-signed cert, with cert checking, on AD connector when it runs on Ubuntu.  e.g. implement a fix similar to the following, but for Ubuntu/linux version of connector.
The change that was done for Windows version:
https://github.com/auth0/ad-ldap-connector/blob/master/lib/add_certs.js#L1-L15

Context for request - customer issue on public chat - Tue July 14, 8:28am & earlier (woloski responded)

This page confirms the location for the certs:  (Note the "Installing the CA" section)
http://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu

Ubuntu page on certificates - possibly useful.
https://help.ubuntu.com/community/GnuTLS

**Comment by troyschneringer** [comment]
Is there any plan to support this for linux as well?
