### ISSUE TITLE
OS X/Linux: current version reports use of old (vulnerable) jsonwebtoken lib

### ISSUE THREAD

**Issue by sebadoom** [auth0/ad-ldap-connector#52]
When installing on Linux the following warnings appear:

npm WARN deprecated jsonwebtoken@4.2.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
npm WARN deprecated jws@2.0.0: Security update: Versions below 3.0.0 are deprecated.

Would a simple version bump work?

**Comment by twistedstream** [comment]
@sebadoom Thanks for reporting. Yes, an upgrade of `jsonwebtoken` and `wsfed` does the trick.
