### ISSUE TITLE
Monitoring/reporting on issues

### ISSUE THREAD

**Issue by joalcorn** [auth0/ad-ldap-connector#61]
We need a way for the connector or the Auth0 dashboard to tell us (either through outbound emails or some form of monitoring web service endpoint) when things go down.

We had an issue where we the Auth0 dashboard said that the connector was offline, but the connector was telling us that it was perfectly fine.  We are unsure how long that situation was in place because the logs for the connector don't show anything, and there is no monitoring of system state available as of yet.

**Comment by twistedstream** [comment]
@joalcorn: Good news. Such a tool now exists:

https://github.com/auth0/auth0-ldap-conector-health-monitor
