### ISSUE TITLE
Installation errors on CentOS 6.7

### ISSUE THREAD

**Issue by yuanzhou** [auth0/ad-ldap-connector#64]
I was trying to install the auth0 connector on CentOS6.7. I followed instructions at https://auth0.com/docs/connector/install-other-platforms

and after I typed `node server.js` I got the following error message:

![e](https://cloud.githubusercontent.com/assets/195873/11667222/6b2cd608-9dbe-11e5-9e38-6f54c487a61b.PNG)

So I guess I'll need to run `npm install` to install all the dependencies.

And I saw the following warning and error messages:

![capture](https://cloud.githubusercontent.com/assets/195873/11667110/e4ed241c-9dbd-11e5-9a70-a617205df79a.PNG)

![capture2](https://cloud.githubusercontent.com/assets/195873/11667117/e6dc9fdc-9dbd-11e5-8358-c4389b838884.PNG)

I also tried `npm i -g auth0/ad-ldap-connector` and got the same warning and error message.

**Comment by twistedstream** [comment]
@yuanzhou what version of Node.js is running on your CentOS server?

**Comment by yuanzhou** [comment]
@twistedstream v0.12.7

**Comment by twistedstream** [comment]
@yuanzhou I think the Connector requires v0.10.x at the moment. Can you try installing that version first and then rerun the Connector install?

**Comment by twistedstream** [comment]
@yuanzhou I just attempted the install with a clean install of CentOS 6.7 in Vagrant and I had to do the following before I could run `node server.js`:
* Perform everything as root (e.g. `sudo su`)
* Install Node.js 0.10 for CentOS (general instructions [here](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora)):  

  ```bash
  curl --silent --location https://rpm.nodesource.com/setup_0.10 | bash -
  yum -y install nodejs
  ```

* Install git:  
  ```bash
  yum -y install git
  ```
* Follow steps 2 & 3 of the [Installing the AD LDAP Connector on different platforms](https://auth0.com/docs/connector/install-other-platforms) page to download the package and copy files to the install directory
* Run `npm install`

While the docs page does say you need to have Node 0.10 installed, it doesn't say to install Git or to run the commands as root. I will get that added today.

**Comment by yuanzhou** [comment]
@twistedstream thanks a lot for the troubleshooting! Much appreciated!

**Comment by twistedstream** [comment]
@yuanzhou Thank you for raising the issue! The [docs page](https://auth0.com/docs/connector/install-other-platforms) has been updated.
