### ISSUE TITLE
Port connector to node.js v >=4

### ISSUE THREAD

**Issue by fredericmora** [auth0/ad-ldap-connector#80]
## Problem
The LDAP connector currenly uses node.js v 0.10. This version goes [EOL on Oct 1st, 2016]( https://github.com/nodejs/LTS).

Code using a dead version of node.js should not be deployed on a production security-critical server. For us at least, this is a blocker that precludes deployment.

## Proposed solution

The connector should be ported to the long-term support version, currently v 4.2.0.

**Comment by Conan-Kudo** [comment]
# Linux distributions and their Node.js versions

Linux distribution | Nodejs version
------------ | -------------
Fedora 24 | 4.5.0
Fedora 25 | 6.5.0
RHEL/CentOS 6 (EPEL) | 0.10.46
RHEL/CentOS 6 (SCL) | [0.10.40](https://www.softwarecollections.org/en/scls/rhscl/nodejs010/)
RHEL/CentOS 7 (EPEL) | 0.10.46 ([upgrading to nodejs 6.5.0](https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/66FOSGNCBZM43I5VSRRLJPFL7Y5PUJ42/))
RHEL/CentOS 7 (SCL) | [0.10.40](https://www.softwarecollections.org/en/scls/rhscl/nodejs010/) and [4.4.2](https://www.softwarecollections.org/en/scls/rhscl/rh-nodejs4/)
openSUSE 42.1 | 0.12.7
openSUSE 42.2 | 4.4.5
Ubuntu 14.04 | 0.10.25
Ubuntu 16.04 | 4.2.6
Debian 8 | 0.10.29
Debian 9 | 4.3.1

As you can see, the major distributions are mostly on nodejs 4.x or 6.x (the current LTSes). Please migrate to nodejs 4 as soon as possible.

**Comment by CriGoT** [comment]
Closed by #79
