### ISSUE TITLE
Old version of  ldapjs npm module causes LDAPS connection error

### ISSUE THREAD

**Issue by vishysank** [auth0/ad-ldap-connector#90]
The version of the ldapjs npm module that is used in the ldap connector is pretty old, and has a bug when being used with ldap (https://github.com/mcavage/node-ldapjs/issues/289). Essentially there needs to be a one line change on  var closeSocket = (opts.secure ? socket.socket : socket); changed to var closeSocket = socket.socket || socket. This has been fixed in newer versions of the ldapjs module,  we made the change in the node_modules file to get it working for now, but it would be great if you can update the version in the package.json of the adapter, and then release a new version of the adaptor, so that we don’t have to maintain this change, especially as we might be dynamically setting up connections.

**Comment by gdestuynder** [comment]
We ran into the same problem, so I PR'd the fix from what we're running - hopefully it helps :)

**Comment by ppaulojr** [comment]
Unfortunately this still doesn't work in the windows version.

![unnamed](https://cloud.githubusercontent.com/assets/1206478/24476528/fb3b0aa4-14a9-11e7-9792-431154704471.png)
